nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.3.cjs

npmRegistries:
  //npm.fontawesome.com:
    npmAlwaysAuth: true
    npmAuthToken: '${FONTAWESOME_NPM_AUTH_TOKEN}'

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmRegistryServer: https://npm.fontawesome.com/
