initScope: npmScopes

nodeLinker: node-modules

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: $FONTAWESOME_NPM_AUTH_TOKEN
    npmRegistryServer: 'https://npm.fontawesome.com'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.6.3.cjs
