nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.3.cjs

initScope: npmScopes

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmRegistryServer: 'https://npm.fontawesome.com'
    npmAuthToken: 0C6FB732-B75E-486A-9C4A-4ACFD7B1C9B8
