nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.3.cjs

npmRegistries:
  '//npm.fontawesome.com/':
    npmAuthToken: $FONTAWESOME_NPM_AUTH_TOKEN

npmScopes:
  fortawesome:
    npmRegistryServer: 'https://npm.fontawesome.com/'
