nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.3.cjs

npmScopes:
  fortawesome:
    npmAuthToken: $FONTAWESOME_NPM_AUTH_TOKEN
    npmAlwaysAuth: true
    npmRegistryServer: 'https://npm.fontawesome.com/'
