nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.3.cjs

initScope: npmScopes

npmRegistries:
  'https://npm.fontawesome.com/':
    npmAuthToken: $FONTAWESOME_NPM_AUTH_TOKEN
    npmAlwaysAuth: true

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmRegistryServer: 'https://npm.fontawesome.com/'
