name: Release Main
#'on':
#  push:
#    branches: ['main']
'on':
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: 'package.json'
      - name: Install dependencies
        run: yarn install
      - name: Build Production
        run: yarn build
  deploy:
    name: Deploy the build to LionDev Cloud
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: 'package.json'
      - name: Install dependencies
        run: yarn install
      - name: Build for deploy
        run: yarn build
      - name: Delete Previous deployment to Alpha LionDev Cloud
        uses: appleboy/ssh-action@v0.1.7
        env:
          DEPLOY_PATH: ${{ vars.MAIN_DEPLOY_PATH }}
        with:
          host: ${{ secrets.STEVISS_SSH_HOST }}
          username: ${{ secrets.STEVISS_SSH_USERNAME }}
          key: ${{ secrets.STEVISS_SSH_KEY }}
          passphrase: ${{ secrets.STEVISS_SSH_PASSPHRASE }}
          port: ${{ secrets.STEVISS_SSH_PORT }}
          envs: DEPLOY_PATH
          script_stop: true
          script: |
            rm -rf ~/$DEPLOY_PATH
      - name: Deploy build to Alpha LionDev Cloud
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.STEVISS_SSH_HOST }}
          username: ${{ secrets.STEVISS_SSH_USERNAME }}
          key: ${{ secrets.STEVISS_SSH_KEY }}
          passphrase: ${{ secrets.STEVISS_SSH_PASSPHRASE }}
          port: ${{ secrets.STEVISS_SSH_PORT }}
          source: 'dist/**'
          target: ${{ vars.MAIN_DEPLOY_PATH }}
          overwrite: true
      - name: Cleanup deployment to Alpha LionDev Cloud
        uses: appleboy/ssh-action@v0.1.7
        env:
          DEPLOY_PATH: ${{ vars.MAIN_DEPLOY_PATH }}
        with:
          host: ${{ secrets.STEVISS_SSH_HOST }}
          username: ${{ secrets.STEVISS_SSH_USERNAME }}
          key: ${{ secrets.STEVISS_SSH_KEY }}
          passphrase: ${{ secrets.STEVISS_SSH_PASSPHRASE }}
          port: ${{ secrets.STEVISS_SSH_PORT }}
          envs: DEPLOY_PATH
          script_stop: true
          script: |
            cd ~/$DEPLOY_PATH
            mv ~/$DEPLOY_PATH/dist/* ~/$DEPLOY_PATH/
            rm -rf ~/$DEPLOY_PATH/dist
