name: Deploy Main

'on':
  workflow_dispatch:

jobs:
  deploy:
    environment: main
    name: Deploy the build to LionDev Cloud
    runs-on: ubuntu-latest
    steps:
      - name: Initial Slack Message
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_BOT_TOKEN: '${{ secrets.SLACK_BOT_TOKEN}}'
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID}}
          payload: |
            {
              "unfurl_links": false,
              "unfurl_media": false,
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "${{ github.workflow }} #${{github.run_number}}"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "image",
                      "image_url": "https://assets.wearelion.dev/astro-icon-slack.png",
                      "alt_text": "Astro Logo"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "Deploying Astro · ID: ${{ github.run_id }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Started by:*\n ${{ github.actor }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Status:*\n ⏳ Working on it..."
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Run>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "<${{ vars.DEPLOY_URL }}|View Enviroment>"
                    }
                  ]
                }
              ]
            }
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version-file: 'package.json'
      - name: Create .env file for frontend
        uses: SpicyPizza/create-envfile@v2.0.2
        with:
          envkey_SANITY_STUDIO_PROJECT_ID: ${{ secrets.SANITY_STUDIO_PROJECT_ID }}
          envkey_SANITY_STUDIO_DATASET: ${{ secrets.SANITY_STUDIO_DATASET }}
          file_name: .env
      - name: Yarn FontAwesome Setup
        env:
          FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
        run: |
          yarn config set initScope npmScopes
          yarn config set npmScopes.fortawesome.npmRegistryServer "https://npm.fontawesome.com"
          yarn config set npmScopes.fortawesome.npmAlwaysAuth true
          yarn config set npmScopes.fortawesome.npmAuthToken $FONTAWESOME_NPM_AUTH_TOKEN
      - name: Yarn Install
        run: yarn install --immutable
      - name: Build for deploy
        run: yarn build
      - name: Delete and Backup Previous deployment to Alpha LionDev Cloud
        id: backup-and-delete
        uses: appleboy/ssh-action@v1.0.0
        env:
          DEPLOY_PATH: ${{ vars.DEPLOY_PATH }}
        with:
          host: ${{ secrets.STEVISS_SSH_HOST }}
          username: ${{ secrets.STEVISS_SSH_USERNAME }}
          key: ${{ secrets.STEVISS_SSH_KEY }}
          passphrase: ${{ secrets.STEVISS_SSH_PASSPHRASE }}
          port: ${{ secrets.STEVISS_SSH_PORT }}
          envs: DEPLOY_PATH
          script_stop: true
          script: |
            mkdir -p ~/temp-backup
            mv ~/$DEPLOY_PATH/* ~/temp-backup/
            rm -rf ~/$DEPLOY_PATH/*
      - name: Deploy build to Alpha LionDev Cloud
        id: deploy
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.STEVISS_SSH_HOST }}
          username: ${{ secrets.STEVISS_SSH_USERNAME }}
          key: ${{ secrets.STEVISS_SSH_KEY }}
          passphrase: ${{ secrets.STEVISS_SSH_PASSPHRASE }}
          port: ${{ secrets.STEVISS_SSH_PORT }}
          source: 'dist/**,.env'
          target: ${{ vars.DEPLOY_PATH }}
          overwrite: true
      - name: Cleanup deployment to Alpha LionDev Cloud
        id: cleanup
        uses: appleboy/ssh-action@v1.0.0
        env:
          DEPLOY_PATH: ${{ vars.DEPLOY_PATH }}
        with:
          host: ${{ secrets.STEVISS_SSH_HOST }}
          username: ${{ secrets.STEVISS_SSH_USERNAME }}
          key: ${{ secrets.STEVISS_SSH_KEY }}
          passphrase: ${{ secrets.STEVISS_SSH_PASSPHRASE }}
          port: ${{ secrets.STEVISS_SSH_PORT }}
          envs: DEPLOY_PATH
          script_stop: true
          script: |
            cd ~/$DEPLOY_PATH
            mv ~/$DEPLOY_PATH/dist/* ~/$DEPLOY_PATH/
            rm -rf ~/$DEPLOY_PATH/dist
            rm -rf ~/temp-backup
      - name: Update Slack Message - Success
        uses: slackapi/slack-github-action@v1.24.0
        if: steps.deploy.outcome == 'success' || steps.cleanup.outcome == 'success' || steps.backup-and-delete.outcome == 'success'
        env:
          SLACK_BOT_TOKEN: '${{ secrets.SLACK_BOT_TOKEN}}'
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID}}
          update-ts: ${{ steps.slack.outputs.ts }}
          payload: |
            {
              "unfurl_links": false,
              "unfurl_media": false,
              "blocks": [
                {
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "${{ github.workflow }} #${{github.run_number}}"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "image",
                      "image_url": "https://assets.wearelion.dev/astro-icon-slack.png",
                      "alt_text": "Astro Logo"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "Deploying Astro · ID: ${{ github.run_id }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Started by:*\n ${{ github.actor }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Status:*\n 🟢 Job Succeeded"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Run>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "<${{ vars.DEPLOY_URL }}|View Enviroment>"
                    }
                  ]
                }
              ]
            }
      - name: RollBack to previous Deployment to Alpha LionDev Cloud
        if: steps.deploy.outcome == 'failure' || steps.cleanup.outcome == 'failure' || steps.backup-and-delete.outcome == 'failure'
        uses: appleboy/ssh-action@v1.0.0
        env:
          DEPLOY_PATH: ${{ vars.DEPLOY_PATH }}
        with:
          host: ${{ secrets.STEVISS_SSH_HOST }}
          username: ${{ secrets.STEVISS_SSH_USERNAME }}
          key: ${{ secrets.STEVISS_SSH_KEY }}
          passphrase: ${{ secrets.STEVISS_SSH_PASSPHRASE }}
          port: ${{ secrets.STEVISS_SSH_PORT }}
          envs: DEPLOY_PATH
          script_stop: true
          script: |
            mv ~/temp-backup/* ~/$DEPLOY_PATH/
            rm -rf ~/temp-backup
      - name: Update Slack Message - Failed
        uses: slackapi/slack-github-action@v1.24.0
        if: steps.deploy.outcome == 'failure' || steps.cleanup.outcome == 'failure' || steps.backup-and-delete.outcome == 'failure'
        env:
          SLACK_BOT_TOKEN: '${{ secrets.SLACK_BOT_TOKEN}}'
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID}}
          update-ts: ${{ steps.slack.outputs.ts }}
          payload: |
            {
              "unfurl_links": false,
              "unfurl_media": false,
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "${{ github.workflow }} #${{github.run_number}}"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "image",
                      "image_url": "https://assets.wearelion.dev/astro-icon-slack.png",
                      "alt_text": "Astro Logo"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "Deploying Astro · ID: ${{ github.run_id }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Started by:*\n ${{ github.actor }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Status:*\n 🔴 Job Failed"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Run>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "<${{ vars.DEPLOY_URL }}|View Enviroment>"
                    }
                  ]
                }
              ]
            }
