name: Slack Testing
#'on':
#  push:
#    branches: ['main']
'on':
  workflow_dispatch:

jobs:
  deploy:
    environment: main
    name: Deploy the build to LionDev Cloud
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: |
          echo "{date}={$(date +'+%Y/%m/%d %H:%M:%S')}" >> $GITHUB_STATE
      - name: Initial Slack Message
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_BOT_TOKEN: '${{ secrets.SLACK_BOT_TOKEN}}'
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID}}
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "${{ github.workflow }} - ${{ github.run_id }}",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "Started by: ${{ github.actor }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Status:*\n ⏳ Working on it..."
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Run>"
                    
                    },
                    {
                      "type": "mrkdwn",
                      "text": "<${{ vars.DEPLOY_URL }}|View Enviroment>"
                    
                    },
                  ]
                }
              ]
            }
